import type {
 LessonContent, OverviewSlide, ExplanationSlide,
 VideoSlide, MCQSlide, CompletionSlide,
} from "@/lib/lesson-types";


// ─────────────────────────────────────────────────────────────
// LESSON 1.1 — What is a Government?
// ─────────────────────────────────────────────────────────────
export const LESSON_1_1: LessonContent = {
 id: "l1-1", levelId: "level-1", number: 1,
 title: "What is a Government?",
 xpReward: 50, badgeId: "first-lesson",
 badgeName: "First Steps", badgeIcon: "👶",
 slides: [
   { id:"l1-1-s1", type:"overview", order:1,
     lessonTitle: "What is a Government?",
     goal: "By the end of this lesson, you will be able to explain what a government is and why every society needs one.",
     bulletPoints: ["What the word 'government' actually means","Why humans need governments to live together","A real Indian example","A quick quiz"],
   } as OverviewSlide,
   { id:"l1-1-s2", type:"explanation", order:2,
     heading: "What is a Government?",
     body: "A government is a group of people who are chosen or elected to make rules and decisions for a country. Their main job is to keep everyone safe, treat people fairly, and make sure the country runs smoothly.",
     imageEmoji: "🏛️",
   } as ExplanationSlide,
   { id:"l1-1-s3", type:"explanation", order:3,
     heading: "Rules are called Laws",
     body: "The rules that a government makes are called laws. Laws tell us what we can and cannot do — for example, everyone must go to school until a certain age, and stealing is not allowed.",
     imageEmoji: "📜",
   } as ExplanationSlide,
   { id:"l1-1-s4", type:"explanation", order:4,
     heading: "Why Do We Need a Government?",
     body: "Imagine a school with no teachers and no rules — it would be chaotic and nobody would be safe! A country is the same. Without a government, there would be no roads, hospitals, or schools — and no one to help when something goes wrong.",
     imageEmoji: "🏫",
   } as ExplanationSlide,
   { id:"l1-1-s5", type:"explanation", order:5,
     heading: "India's Government",
     body: "India has a democratic government — the people of India choose who will lead them. Every few years, Indians vote to elect their leaders. Those elected leaders make decisions for the entire country from Parliament in New Delhi.",
     imageEmoji: "🇮🇳",
   } as ExplanationSlide,
   { id:"l1-1-s6", type:"video", order:6,
     title: "How does a government work?",
     videoUrl: "https://www.youtube.com/embed/OgVKvqTItto",
     duration: "5 min", sourceCredit: "TED-Ed",
   } as VideoSlide,
   { id:"l1-1-s7", type:"mcq", order:7,
     question: "What does a government mainly do?",
     isRolePlay: false, imageEmoji: "🤔",
     options: [
       { id:"a", text:"Makes and enforces rules for the country", icon:"📜", isCorrect:true  },
       { id:"b", text:"Runs shops and sells things to people",    icon:"🛒", isCorrect:false },
       { id:"c", text:"Teaches children in schools",              icon:"✏️", isCorrect:false },
       { id:"d", text:"Builds games and parks only",              icon:"🎡", isCorrect:false },
     ],
     explanation: "A government's main job is to make laws and decisions that keep everyone safe and treat people fairly.",
   } as MCQSlide,
   { id:"l1-1-s8", type:"mcq", order:8,
     question: "What should you do first?",
     isRolePlay: true,
     roleContext: "You are the new Prime Minister of India. A flood has hit a village in Kerala and people need help.",
     imageEmoji: "🌊",
     options: [
       { id:"a", text:"Wait and see what happens next week",        icon:"⏳", isCorrect:false },
       { id:"b", text:"Send rescue teams and supplies immediately", icon:"🚁", isCorrect:true  },
       { id:"c", text:"Ask the villagers to solve it themselves",   icon:"🤷", isCorrect:false },
       { id:"d", text:"Hold a meeting to discuss it for a month",  icon:"📅", isCorrect:false },
     ],
     explanation: "A government's most important duty is protecting its citizens in emergencies. A quick response saves lives.",
   } as MCQSlide,
   { id:"l1-1-s9", type:"completion", order:9,
     xpEarned:50, badgeId:"first-lesson", badgeName:"First Steps", badgeIcon:"👶",
   } as CompletionSlide,
 ],
};


// ─────────────────────────────────────────────────────────────
// LESSON 1.2 — Why Do We Have Rules?
// ─────────────────────────────────────────────────────────────
export const LESSON_1_2: LessonContent = {
 id: "l1-2", levelId: "level-1", number: 2,
 title: "Why Do We Have Rules?",
 xpReward: 50,
 slides: [
   { id:"l1-2-s1", type:"overview", order:1,
     lessonTitle: "Why Do We Have Rules?",
     goal: "By the end of this lesson, you will be able to describe at least two reasons why rules are necessary for a society to function fairly.",
     bulletPoints: ["What rules are and where they come from","Why life without rules would be unfair","How rules protect everyone","A quick quiz"],
   } as OverviewSlide,
   { id:"l1-2-s2", type:"explanation", order:2,
     heading: "What are Rules?",
     body: "Rules are guidelines that tell us how to behave in a group or community. Rules exist everywhere — at home, at school, on the road, and in the country. Without rules, everyone would do whatever they wanted, which would make life very difficult for others.",
     imageEmoji: "📋",
   } as ExplanationSlide,
   { id:"l1-2-s3", type:"explanation", order:3,
     heading: "Rules Keep Us Safe",
     body: "Many rules exist to protect us from harm. Traffic lights tell us when to stop and go — without them, accidents would happen constantly. Safety rules in schools, factories, and hospitals save thousands of lives every day.",
     imageEmoji: "🚦",
   } as ExplanationSlide,
   { id:"l1-2-s4", type:"explanation", order:4,
     heading: "Rules Make Things Fair",
     body: "Imagine a cricket match where one team could change the rules whenever they were losing. That would not be fair! Rules make sure everyone is treated equally and that no one person has too much power over others.",
     imageEmoji: "🏏",
   } as ExplanationSlide,
   { id:"l1-2-s5", type:"explanation", order:5,
     heading: "Rules in India",
     body: "India's Constitution is the biggest rulebook in the country. It contains rules that apply to every single Indian — from students to the Prime Minister. The Constitution says that no one, not even the most powerful person, is above the law.",
     imageEmoji: "⚖️",
   } as ExplanationSlide,
   { id:"l1-2-s6", type:"mcq", order:6,
     question: "A student keeps pushing others in the lunch queue and takes extra food. What does this show?",
     isRolePlay: false, imageEmoji: "🍱",
     options: [
       { id:"a", text:"Rules are not needed in small places like schools", icon:"❌", isCorrect:false },
       { id:"b", text:"Without rules, some people take advantage of others", icon:"✅", isCorrect:true },
       { id:"c", text:"Food should only be given to strong students", icon:"💪", isCorrect:false },
       { id:"d", text:"The student is the fastest so they deserve more", icon:"🏃", isCorrect:false },
     ],
     explanation: "Without rules, stronger or pushier people take advantage of others. Rules protect everyone — especially those who are quieter or smaller.",
   } as MCQSlide,
   { id:"l1-2-s7", type:"mcq", order:7,
     question: "Which of these is the best reason why India has a Constitution?",
     isRolePlay: false, imageEmoji: "📖",
     options: [
       { id:"a", text:"To make the country look important to other nations", icon:"🌍", isCorrect:false },
       { id:"b", text:"To give the Prime Minister unlimited power",          icon:"👑", isCorrect:false },
       { id:"c", text:"To have rules that treat every Indian fairly and equally", icon:"⚖️", isCorrect:true },
       { id:"d", text:"To decide which languages people must speak",         icon:"🗣️", isCorrect:false },
     ],
     explanation: "The Constitution exists to make sure that every Indian — regardless of who they are — is treated fairly and has the same basic rights.",
   } as MCQSlide,
   { id:"l1-2-s8", type:"completion", order:8,
     xpEarned:50,
   } as CompletionSlide,
 ],
};


// ─────────────────────────────────────────────────────────────
// LESSON 1.3 — How India's Government Works
// ─────────────────────────────────────────────────────────────
export const LESSON_1_3: LessonContent = {
 id: "l1-3", levelId: "level-1", number: 3,
 title: "How India's Government Works",
 xpReward: 75,
 slides: [
   { id:"l1-3-s1", type:"overview", order:1,
     lessonTitle: "How India's Government Works",
     goal: "By the end of this lesson, you will be able to name the three branches of India's government and explain what each one does.",
     bulletPoints: ["The three branches of government","What the Parliament does","What the President and Prime Minister do","How courts protect your rights","A quick quiz"],
   } as OverviewSlide,
   { id:"l1-3-s2", type:"explanation", order:2,
     heading: "Three Branches of Government",
     body: "India's government is divided into three parts, called branches. Each branch has a different job, and they check each other's work to make sure no single person or group becomes too powerful. Think of it like three friends keeping each other honest.",
     imageEmoji: "🌳",
   } as ExplanationSlide,
   { id:"l1-3-s3", type:"explanation", order:3,
     heading: "The Legislature — Parliament",
     body: "Parliament is made up of elected representatives chosen by Indian citizens. Parliament's job is to make laws. It has two houses: the Lok Sabha (House of the People) and the Rajya Sabha (Council of States). When Parliament passes a law, it applies to every Indian.",
     imageEmoji: "🏛️",
   } as ExplanationSlide,
   { id:"l1-3-s4", type:"explanation", order:4,
     heading: "The Executive — The Government",
     body: "The Executive branch runs the country day to day. It is led by the Prime Minister, who is the head of government. The Prime Minister is chosen from the party that wins the most seats in Parliament. The President of India is the constitutional head — a ceremonial role that officially approves laws.",
     imageEmoji: "👔",
   } as ExplanationSlide,
   { id:"l1-3-s5", type:"explanation", order:5,
     heading: "The Judiciary — The Courts",
     body: "The Supreme Court of India is the highest court in the country. The Judiciary's job is to make sure laws are fair and follow the Constitution. If the government makes a law that breaks the Constitution, the Supreme Court can cancel it. This protects every citizen's rights.",
     imageEmoji: "⚖️",
   } as ExplanationSlide,
   { id:"l1-3-s6", type:"mcq", order:6,
     question: "Which branch of India's government makes new laws?",
     isRolePlay: false, imageEmoji: "📝",
     options: [
       { id:"a", text:"The Supreme Court (Judiciary)",      icon:"⚖️", isCorrect:false },
       { id:"b", text:"The Parliament (Legislature)",       icon:"🏛️", isCorrect:true  },
       { id:"c", text:"The Prime Minister's Office alone",  icon:"👔", isCorrect:false },
       { id:"d", text:"The President of India alone",       icon:"🎖️", isCorrect:false },
     ],
     explanation: "Parliament is the Legislature — its main job is to debate and pass laws that apply to the whole country.",
   } as MCQSlide,
   { id:"l1-3-s7", type:"mcq", order:7,
     question: "What would you do as a Supreme Court judge if Parliament passed a law that said only rich people could vote?",
     isRolePlay: true,
     roleContext: "You are a Supreme Court judge. Parliament has just passed a law saying only people who earn more than ₹10 lakh per year can vote in elections.",
     imageEmoji: "👨‍⚖️",
     options: [
       { id:"a", text:"Follow the law — Parliament always knows best",    icon:"🤐", isCorrect:false },
       { id:"b", text:"Cancel the law — it goes against the Constitution", icon:"❌", isCorrect:true  },
       { id:"c", text:"Ask the President to decide",                      icon:"📨", isCorrect:false },
       { id:"d", text:"Ignore the law and do nothing",                    icon:"😶", isCorrect:false },
     ],
     explanation: "The Supreme Court's job is to protect the Constitution. A law that stops poor people from voting goes against the fundamental right to equality — the court must cancel it.",
   } as MCQSlide,
   { id:"l1-3-s8", type:"completion", order:8,
     xpEarned:75,
   } as CompletionSlide,
 ],
};


// ─────────────────────────────────────────────────────────────
// LESSON 1.4 — The Constitution Explained
// ─────────────────────────────────────────────────────────────
export const LESSON_1_4: LessonContent = {
 id: "l1-4", levelId: "level-1", number: 4,
 title: "The Constitution Explained",
 xpReward: 75, badgeId: "level-1-complete",
 badgeName: "Foundations Unlocked", badgeIcon: "🏛️",
 slides: [
   { id:"l1-4-s1", type:"overview", order:1,
     lessonTitle: "The Constitution Explained",
     goal: "By the end of this lesson, you will be able to explain what the Constitution is and why it is the most important document in India.",
     bulletPoints: ["What a Constitution is","Why India needed one","The Preamble — the opening promise","Your Fundamental Rights","A quick quiz"],
   } as OverviewSlide,
   { id:"l1-4-s2", type:"explanation", order:2,
     heading: "What is a Constitution?",
     body: "A Constitution is the most important document of a country. It sets the rules for how the government works, what rights every citizen has, and what no one — not even the Prime Minister — is allowed to do. India's Constitution came into effect on 26 January 1950, which is why we celebrate Republic Day.",
     imageEmoji: "📗",
   } as ExplanationSlide,
   { id:"l1-4-s3", type:"explanation", order:3,
     heading: "Why India Needed a Constitution",
     body: "When India became independent in 1947, the leaders had to decide: how should this new country be run? Who gets power? How do we make sure everyone is treated fairly? Dr. B.R. Ambedkar led the team that wrote the Constitution — it took almost three years to write and is the longest national constitution in the world.",
     imageEmoji: "🇮🇳",
   } as ExplanationSlide,
   { id:"l1-4-s4", type:"explanation", order:4,
     heading: "The Preamble — India's Opening Promise",
     body: "The Preamble is the opening paragraph of the Constitution. It begins with the words: 'We, the People of India...' This means the power in India comes from its citizens — not from kings or rulers. It promises that India will be a Sovereign, Socialist, Secular, Democratic Republic.",
     imageEmoji: "✍️",
   } as ExplanationSlide,
   { id:"l1-4-s5", type:"explanation", order:5,
     heading: "Your Fundamental Rights",
     body: "The Constitution gives every Indian six Fundamental Rights — rights so important that no law can take them away. These include: the Right to Equality (everyone is equal before the law), the Right to Freedom (freedom of speech, movement, and more), and the Right to Education (free schooling for all children aged 6–14).",
     imageEmoji: "🤝",
   } as ExplanationSlide,
   { id:"l1-4-s6", type:"mcq", order:6,
     question: "When did India's Constitution come into effect?",
     isRolePlay: false, imageEmoji: "📅",
     options: [
       { id:"a", text:"15 August 1947 — Independence Day",    icon:"🎉", isCorrect:false },
       { id:"b", text:"26 January 1950 — Republic Day",       icon:"📗", isCorrect:true  },
       { id:"c", text:"2 October 1869 — Gandhi's birthday",   icon:"🕊️", isCorrect:false },
       { id:"d", text:"14 November 1889 — Nehru's birthday",  icon:"🌹", isCorrect:false },
     ],
     explanation: "India's Constitution came into effect on 26 January 1950 — which is why we celebrate Republic Day on that date every year.",
   } as MCQSlide,
   { id:"l1-4-s7", type:"mcq", order:7,
     question: "Your school has started charging fees and refusing admission to poor students. What right does this violate?",
     isRolePlay: false, imageEmoji: "🏫",
     options: [
       { id:"a", text:"Right to Freedom of Speech",            icon:"🗣️", isCorrect:false },
       { id:"b", text:"Right to Education",                    icon:"📚", isCorrect:true  },
       { id:"c", text:"Right to vote in elections",            icon:"🗳️", isCorrect:false },
       { id:"d", text:"Right to own property",                 icon:"🏠", isCorrect:false },
     ],
     explanation: "The Right to Education guarantees free and compulsory education to all children aged 6–14. Charging fees and excluding poor students directly violates this Fundamental Right.",
   } as MCQSlide,
   { id:"l1-4-s8", type:"completion", order:8,
     xpEarned:75, badgeId:"level-1-complete",
     badgeName:"Foundations Unlocked", badgeIcon:"🏛️",
   } as CompletionSlide,
 ],
};


// ─────────────────────────────────────────────────────────────
// LESSON REGISTRY
// ─────────────────────────────────────────────────────────────
export const LESSONS: Record<string, LessonContent> = {
 "l1-1": LESSON_1_1,
 "l1-2": LESSON_1_2,
 "l1-3": LESSON_1_3,
 "l1-4": LESSON_1_4,
 // Level 2 and 3 to be added when scripts are ready
};





